
GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
       "title": "I miss WOW",
       "author": "Michael Christman",
       "url": "blizzard.com",
       "likes": 2000
}